# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# Windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]


# Middleman Gems
gem 'middleman',      '>= 4.0.0'
gem 'middleman-blog'
